import { chromium } from '@playwright/test'
const b = await chromium.launch({ channel: 'chrome', args: ['--enable-gpu', '--ignore-gpu-blocklist', '--use-angle=metal'] })
const p = await b.newPage({ viewport: { width: 1400, height: 900 } })
const errors = []; p.on('pageerror', e => errors.push(e.message)); p.on('console', m => (m.type() === 'error' || m.type() === 'warning') && errors.push(m.text().slice(0, 200)))
await p.goto('http://localhost:5173/dev/cube'); await p.waitForFunction(() => !!window.__nav3d); await p.waitForTimeout(2500)
const cam = () => p.evaluate(() => window.__nav3d.camera.position.toArray().map((v) => +v.toFixed(2)))
const home = await cam()
await p.mouse.move(700, 450); await p.mouse.down(); await p.mouse.move(400, 300, { steps: 12 }); await p.mouse.up(); await p.waitForTimeout(600)
const moved = await cam()
await p.getByRole('button', { name: /Re-center/ }).click(); await p.waitForTimeout(1500)
const back = await cam()
await p.mouse.move(700, 450); await p.mouse.down(); await p.mouse.move(900, 500, { steps: 12 }); await p.mouse.up(); await p.waitForTimeout(400)
await p.keyboard.press('r'); await p.waitForTimeout(1500)
const backKey = await cam()
console.log(JSON.stringify({ home, moved, back, backKey, errors }))
await b.close()
